# Generated by Django 5.0.4 on 2024-06-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hello',
            table='hello',
        ),
    ]
